name = "sert"

main = "./.output/server/index.mjs"
workers_dev = true
compatibility_date = "2024-10-27"

rules = [{ type = "ESModule", globs = ["**/*.js", "**/*.mjs"] }]

kv_namespaces = [{ binding = "sert-kv", id = "b11e322d9c3745edbe58f16206d19ead" }]

[triggers]
crons = ["9,39 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1
