name: API

on:
  workflow_run:
    workflows: [ Release ]
    types: [ completed ]

  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install

      - name: Build server code
        run: pnpm api:build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            api/.output
            api/wrangler.toml
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: cloudflare
      url: https://sert.somespecialone.workers.dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .output

      - name: Move deploy configuration
        run: mv .output/wrangler.toml .

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
