name: Push to deta branch

on:
  release:
    types: [ published ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Move files to root"
        run: |
          git rm -rf .
          git checkout HEAD -- service
          cp service/* . -r
          git rm -rf service

      - name: "Commit & push files to deta branch"
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: deta-branch
