name: Push to deta branch

on:
  push:
    branches: [ "master" ]
    paths: [ "service/**", ".github/workflows/deta-branch.yml" ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Move files to root"
        run: |
          git rm -rf .
          git checkout HEAD -- service
          cp service/* .
          git rm -rf service

      - name: "Commit & push files to deta branch"
        uses: EndBug/add-and-commit@v9
        with:
          fetch: false
          new_branch: deta-branch
