name: Deploy Service

on:
  release:
    types: [ published ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Deploy app to Deta"
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }}
          deta-name: "steam-exchange-rate-tracker"
          deta-project-dir: service
