name: Tests

on:
  push:
    branches: [ master ]
    paths: [ "backend/src", "backend/tests", "backend/package.json" ]

jobs:
  test_back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: "backend/pnpm-lock.yaml"
      - run: pnpm install

      - name: "Run Jest tests with coverage"
        env:
          DETA_BASE_NAME: "test-base"
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
        run: pnpm jest tests --ci --coverage

      - name: "Upload coverage report to Codecov"
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

        timeout-minutes: 10
