name: Deploy Web-app

on:
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./web-app
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install and build app"
        env:
          VITE_API_URL: "https://steam-exchange-rate-tracker.deta.dev"
        run: |
          pnpm install
          pnpm build

      - name: "Building and deploying to GitHub Pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web-app/dist
          cname: sert.somespecial.one
